---
- name: Install N98 Magerun
  command: curl -o /usr/local/bin/n98-magerun https://raw.githubusercontent.com/netz98/n98-magerun/master/n98-magerun.phar creates=/usr/local/bin/n98-magerun

- name: Make N98 executable
  file: path=/usr/local/bin/n98-magerun mode="755"
